!!com.rabit.featuremigration.beans.vcstructure.ConfigManifest
packageDirectories:
  packagePaths:
    dataset:
      features:
        01dHmT01-UI:
          path: dataset/01dHmT01-UI
          prefix: ncino
          standardFeature: false
          versions:
            Fall 2019:
              modifiedDate: '2021-06-16 19:06:03'
